### ISSUE TITLE
hello!! I want to ask you a question!!

### ISSUE THREAD

**Issue by Lee-Seong-Ju** [mogemimi/pomdog#38]
hello i dont well write english so please undertasnd me.
im "clone" to "pomdog" and I proceeded to here "git submodule update --init" but i cant go in 
"cd path/to/pomdog" -> no directory path,,,,, how to next proceed?? sorry,,,I've just started GitHub,,

**Comment by mogemimi** [comment]
Hello,
The example `path/to/pomdog` in the [`README`](https://github.com/mogemimi/pomdog/blob/master/README.md) indicates the location of the git directory you cloned. If you have cloned to the directory `C:\Users\Me\pomdog`, `path/to/pomdog` is `C:\Users\Me\pomdog` as follows:

```sh
cd C:\Users\Me
git clone https://github.com/mogemimi/pomdog.git

# The following line corresponds to `cd path/to/pomdog` in the example.
cd pomdog

git submodule update --init --recursive

# Generate projects for Visual Studio 2019
cmake -Bbuild.cmake -H. -G "Visual Studio 16"
```

Please also refer to the following page:
https://github.com/mogemimi/pomdog/blob/master/docs/Getting-Started.md

And if you have any questions about the documentation, feel free to let me know :smiley_cat:

**Comment by Lee-Seong-Ju** [comment]
ㅠㅠㅠ So sorry,,,,additionary i ask you one more question....sorry.
I already clone and init excuting,,
C:\Users\seongju\Documents\GitHub\pomdog  <= this my directory,,,

and i try this
# Generate projects for Visual Studio 2019 
cmake -Bbuild.cmake -H. -G "Visual Studio 16"

but 
bash: cmake: command not found
this problem has occurred,,,,

how can i solved this problem,,ㅠㅠ 
very very sorry

**Comment by mogemimi** [comment]
You're getting this error because you don't have the CMake command installed. So you can download the CMake installer from the following link:
https://cmake.org/download/

If an "Add CMake to the system PATH" install option is selected during installation, the `cmake` command can be automatically set to the environment variable `PATH`. If you manually add an environment variable, you have to set the following to the `PATH`:
```
C:\Program Files\CMake\bin
```

Finally, please run the following command to make sure `cmake` command is installed:

```sh
cmake --version
```
