### ISSUE TITLE
Crash when the cursor is over the window just created, on Windows

### ISSUE THREAD

**Issue by Bakedanuki** [mogemimi/pomdog#39]
初めてのissueです。間違っていればご指摘お願いたします。

##実行環境
OS Windows10
アプリケーション VisualStdio2017

##再現手順
Windows環境でビルドし実行し、ウィンドウが生成されたタイミングでカーソルがウィンドウとかぶっていると落ちる。

##期待される結果

GameWindowWin32::Impl::WindowProcedure関数のWM_SETCURSOR内の処理がウィンドウ生成時にwindow変数が初期化されていないにもかかわらず処理されているのが原因だと思われます。

case WM_SETCURSOR: {
    if (window)
    {
      auto hitTest = lParam & 0xffff;
      if (hitTest == HTCLIENT && window->gameCursor)
      {
        SetCursor(*window->gameCursor);
        return FALSE;
      }
    }
    break;
  }
が正しい挙動ではないでしょうか。

**Comment by mogemimi** [comment]
Hi, thank you for reporting this issue. I will take a look to fix it.

こんにちは、報告ありがとうございます。さっそく修正いたします。 🐛 👍 

-----

### Translation:

##### Developing environments
- Windows 10, Visual Studio 2017

##### Steps to Reproduce

1. Build and run in Windows.
2. If the mouse cursor is over the window when the window is created, it will crash.

#### Expected behavior

The reason is that although `window` variable is not initialized when the window is created, `window` can be accessed in the `WM_SETCURSOR` case in `GameWindowWin32::Impl::WindowProcedure` function.

With `if (window != nullptr)` statement added, the application is not crash.

```cpp
case WM_SETCURSOR: {
    if (window) {
        auto hitTest = lParam & 0xffff;
        if (hitTest == HTCLIENT && window->gameCursor) {
            SetCursor(*window->gameCursor);
            return FALSE;
        }
    }
    break;
}
```

**Comment by mogemimi** [comment]
I've just fixed it and it's merged to master. #40
