### ISSUE TITLE
Running on Mac

### ISSUE THREAD

**Issue by Bakedanuki** [mogemimi/pomdog#41]
こんにちは。
Mac初心者なので認識などが間違っている可能性があります。ご了承ください。

### 実行環境
OS macOS Catalina 10.15.3
XCode 10.15.3

### 再現手順
手順通りビルドしFeatureShowcaseを実行しようとしたところ画面が白いままで何も出ませんでした。
またxcodeprojで実行したところ実行結果が4分の1のサイズで出力されます。
appの内容を表示し実行ファイルそのものを実行したところ
`-[NSNib _initWidthNibNamed:bundle:option:] could not load the nibName : PomdogViewController in bundle (null)`
と表示されています。
恐らくですがMainMenu.xibが原因でしょうか。

どうぞよろしくお願いいたします。

**Comment by mogemimi** [comment]
### Translation:

Hello, I'm a Mac newbie, so sorry if I'm getting those issues wrong.

#### Developing environments
OS macOS Catalina 10.15.3
XCode 10.15.3

#### Steps to Reproduce
I tried to build and run the FeatureShowcase app according to the documentation, but the screen is still nothing appeared. In addition, when running with xcodeproj, the output result is a quarter of the original size.
When the executable file was directly executed, the following message was output:
```
-[NSNib _initWidthNibNamed:bundle:option:] could not load the nibName : PomdogViewController in bundle (null)
```

I think perhaps MainMenu.xib is the cause.
Thanks.

**Comment by mogemimi** [comment]
こんにちは、報告ありがとうございます。

ウィンドウに何も表示されない不具合は、 CMake で `MetalKit.framework` をリンクし忘れていたのが原因のようです。すぐに修正いたします。

4分の1のサイズで表示されてしまうバグは、 Metal のレンダラーが Retina ディスプレイにまだ対応していないことが原因です。 Mac Book や iMac などの Retina ディスプレイ上で表示したときに起こりえます。少し時間はかかりますが、 Retina ディスプレイに対応してみます。

修正されるまでの間、 Metal の代わりに OpenGL を使うことも可能です。OpenGL で描画する場合は、 Retina ディスプレイでも問題なく等倍で表示されます(おそらく)。
Metal の代わりに OpenGL を使う場合は、`pomdog/examples/FeatureShowcase/Platform.Cocoa/AppDelegate.mm` を次のように編集します:

```cpp
// true にすると OpenGL が使えます
bootstrap.SetOpenGLEnabled(true);
```

----

Hello, thank you for reporting!

First, the bug that nothing is displayed in the window is caused by forgetting to link `MetalKit.framework` in CMake. It's a simple thing to fix and I will fix it soon.

Second, the bug that the screen is displayed at a quarter size is due to the Metal renderer not fully supporting the Retina display. This can happen when viewed on a Retina display such as a Mac Book or iMac. I will try to support Retina display but I think it will take some time.

Finally, you can use OpenGL instead of Metal until the bug is fixed. If you draw using OpenGL, it will be (maybe) displayed at 1:1 without any problem on a Retina display.

To use OpenGL instead of Metal on macOS, edit `pomdog/examples/FeatureShowcase/Platform.Cocoa/AppDelegate.mm` as follows:

```cpp
// Set to true to use OpenGL
bootstrap.SetOpenGLEnabled(true);
```

**Comment by Bakedanuki** [comment]
ご返事ありがとうございます。
なるほど理解できました！ありがとうございます。
ただ早速OpenGLで実行しようと書き換えビルドしたところ
`CVDisplayLink (13): EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`
のエラーが出力されました。

**Comment by mogemimi** [comment]
### Translation:

Thank you for replying, now I got it! Although I tried to modify to OpenGL and build it, I get the following error.

```
CVDisplayLink (13): EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
```

**Comment by mogemimi** [comment]
おお、 macOS の OpenGL レンダラーでは、ゲームループを CVDisplayLink のサブスレッドで直接実行しているのが原因かもしれません。メインスレッドでゲームループを回すように修正してみます。

In the OpenGL renderer on macOS, it may be because the game loop is running directly on the CVDisplayLink subthread. I'll modify to run the game loop in the main thread.

**Comment by Bakedanuki** [comment]
ありがとうございます。
Metalは正しく動作していました。
ただOpenGLも4分の1のサイズになりその他の部分にはノイズのような描画がされました。
これもRetinaディスプレイのせいかもしれません。

**Comment by mogemimi** [comment]
#### Translation:

Thank you. Metal works fine but it is drawn in a quarter size with OpenGL too, and noise is drawn to the rest of the space. This may also be due to the Retina display.

**Comment by mogemimi** [comment]
The PR https://github.com/mogemimi/pomdog/pull/43 fixed it for Metal and OpenGL. This change is temporary workaround, and there are plans to provide high-resolution support in the future for retina display.

プルリクエスト https://github.com/mogemimi/pomdog/pull/43 で修正しました。
この変更は一時的なワークアラウンドで、もう少しちゃんとした retina ディスプレイのサポートを今後行う予定です。

**Comment by Bakedanuki** [comment]
ありがとうございました!
きちんと動作していました!!
これからも楽しみにしています👍

**Comment by mogemimi** [comment]
(Translation)
Thank you! It works well now. Look forward to your update!

-----

Thank you for confirming! I will proceed with retina support.

動作確認ありがとうございます！引き続き Retina 対応を進めます。
